apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dojo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
        - name: appc
          image: sarraragguem/guestbook:v0.1.0
          command: ["./binary"]
          ports: 
            - containerPort: 3000
              name: http
          env:
            - name: REDIS_HOST
              value: "dojo-redis"
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
