apiVersion: v1
kind: Service
metadata:
  name: dojo-metrics
  namespace: dojonm
  labels:
    app: dojo
    release: kube-prom
spec:
  selector:
    foo: bar
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dojo-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom          # must match
spec:
  namespaceSelector:
    matchNames: ["dojonm"]
  selector:
    matchLabels:
      release: kube-prom
      app: dojo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s