apiVersion: v1
kind: Pod
metadata:
  name: dojo-pod
  namespace: dojonm
  labels:
    foo: bar
spec:
  volumes:
    - name: db-data
      emptyDir: {}
  containers:
    - name: appc
      image: sarraragguem/guestbook:v0.1.0
      command: ["./binary"]
      ports: 
      - containerPort: 3000
      env:
      - name: REDIS_HOST
        value: redis
    - name: dbc
      image: redis:7-alpine
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: /data
          name: db-data


    